import type { User, Course, Enrollment, CourseRequest, Review } from './types';

export const mockUsers: User[] = [
  {
    id: 'admin_1',
    name: 'Alex Morgan',
    email: 'admin@nextforge.academy',
    role: 'admin',
    isVerified: true,
    isApproved: true,
    isSuspended: false,
    createdAt: '2024-01-01T00:00:00Z',
    bio: 'Platform Administrator',
    enrolledCourses: [],
    completedCourses: [],
    certificates: [],
  },
  {
    id: 'instructor_1',
    name: 'Dr. Sarah Chen',
    email: 'sarah@nextforge.academy',
    role: 'instructor',
    isVerified: true,
    isApproved: true,
    isSuspended: false,
    createdAt: '2024-01-15T00:00:00Z',
    bio: 'Full-Stack Engineer with 10+ years experience. Former Google engineer.',
    enrolledCourses: [],
    completedCourses: [],
    certificates: [],
  },
  {
    id: 'instructor_2',
    name: 'Marcus Johnson',
    email: 'marcus@nextforge.academy',
    role: 'instructor',
    isVerified: true,
    isApproved: true,
    isSuspended: false,
    createdAt: '2024-02-01T00:00:00Z',
    bio: 'Data Science & ML expert. PhD in Computer Science from MIT.',
    enrolledCourses: [],
    completedCourses: [],
    certificates: [],
  },
  {
    id: 'instructor_3',
    name: 'Priya Patel',
    email: 'priya@nextforge.academy',
    role: 'instructor',
    isVerified: true,
    isApproved: false,
    isSuspended: false,
    createdAt: '2024-03-01T00:00:00Z',
    bio: 'Cloud & DevOps specialist. AWS Solutions Architect.',
    enrolledCourses: [],
    completedCourses: [],
    certificates: [],
  },
  {
    id: 'student_1',
    name: 'Jordan Lee',
    email: 'student@nextforge.academy',
    role: 'student',
    isVerified: true,
    isApproved: true,
    isSuspended: false,
    createdAt: '2024-02-10T00:00:00Z',
    bio: 'Aspiring full-stack developer',
    enrolledCourses: ['course_1', 'course_2'],
    completedCourses: [],
    certificates: [],
  },
  {
    id: 'student_2',
    name: 'Emma Wilson',
    email: 'emma@example.com',
    role: 'student',
    isVerified: true,
    isApproved: true,
    isSuspended: false,
    createdAt: '2024-02-20T00:00:00Z',
    enrolledCourses: ['course_1'],
    completedCourses: ['course_3'],
    certificates: [],
  },
  {
    id: 'student_3',
    name: 'Carlos Rivera',
    email: 'carlos@example.com',
    role: 'student',
    isVerified: true,
    isApproved: true,
    isSuspended: false,
    createdAt: '2024-03-05T00:00:00Z',
    enrolledCourses: ['course_2', 'course_3'],
    completedCourses: [],
    certificates: [],
  },
];

export const mockCourses: Course[] = [
  {
    id: 'course_1',
    title: 'Complete Full-Stack Web Development Bootcamp',
    slug: 'full-stack-web-development',
    description: 'Master React, Node.js, PostgreSQL, and deploy production apps from scratch.',
    longDescription: 'This comprehensive bootcamp takes you from zero to production-ready full-stack developer. You will build real-world projects using the most in-demand technologies: React 18, TypeScript, Node.js, Express, PostgreSQL with Prisma ORM, and deploy to cloud platforms. By the end, you will have a professional portfolio of 5+ production applications.',
    thumbnail: 'https://images.unsplash.com/photo-1517180102446-f3ece451e9d8?w=800&q=80',
    instructorId: 'instructor_1',
    instructorName: 'Dr. Sarah Chen',
    instructorAvatar: 'https://images.unsplash.com/photo-1494790108755-2616b612b1e0?w=100&q=80',
    category: 'Web Development',
    level: 'Beginner',
    price: 89.99,
    isFree: false,
    isFeatured: true,
    isPublished: true,
    isApproved: true,
    rating: 4.8,
    reviewCount: 2847,
    enrolledCount: 12450,
    duration: '42 hours',
    tags: ['React', 'Node.js', 'PostgreSQL', 'TypeScript', 'Full-Stack'],
    requirements: ['Basic HTML/CSS knowledge', 'Computer with internet access', 'Willingness to learn'],
    whatYouLearn: [
      'Build full-stack apps with React & Node.js',
      'Design and manage PostgreSQL databases',
      'Implement JWT authentication',
      'Deploy apps to production',
      'Write clean, maintainable TypeScript code',
      'Use Git and modern development workflows',
    ],
    modules: [
      {
        id: 'mod_1_1',
        courseId: 'course_1',
        title: 'Getting Started with Web Development',
        order: 1,
        lessons: [
          { id: 'les_1_1_1', moduleId: 'mod_1_1', title: 'Course Introduction & Setup', type: 'video', duration: '12:30', isPreview: true, order: 1 },
          { id: 'les_1_1_2', moduleId: 'mod_1_1', title: 'How the Web Works', type: 'video', duration: '18:45', isPreview: true, order: 2 },
          { id: 'les_1_1_3', moduleId: 'mod_1_1', title: 'Development Environment Setup', type: 'video', duration: '25:10', isPreview: false, order: 3 },
          { id: 'les_1_1_4', moduleId: 'mod_1_1', title: 'Module 1 Resources', type: 'pdf', isPreview: false, order: 4 },
          { id: 'les_1_1_5', moduleId: 'mod_1_1', title: 'Module 1 Quiz', type: 'quiz', isPreview: false, order: 5, quiz: { id: 'quiz_1', lessonId: 'les_1_1_5', questions: [{ id: 'q1', question: 'What does HTML stand for?', options: ['HyperText Markup Language', 'High Tech Modern Language', 'Home Tool Markup Language', 'Hyper Transfer Markup Language'], correctIndex: 0 }, { id: 'q2', question: 'Which protocol does the web use?', options: ['FTP', 'HTTP/HTTPS', 'SMTP', 'SSH'], correctIndex: 1 }] } },
        ],
      },
      {
        id: 'mod_1_2',
        courseId: 'course_1',
        title: 'React Fundamentals',
        order: 2,
        lessons: [
          { id: 'les_1_2_1', moduleId: 'mod_1_2', title: 'Introduction to React', type: 'video', duration: '20:00', isPreview: false, order: 1 },
          { id: 'les_1_2_2', moduleId: 'mod_1_2', title: 'Components & Props', type: 'video', duration: '35:15', isPreview: false, order: 2 },
          { id: 'les_1_2_3', moduleId: 'mod_1_2', title: 'State & Hooks', type: 'video', duration: '42:00', isPreview: false, order: 3 },
          { id: 'les_1_2_4', moduleId: 'mod_1_2', title: 'Build a Todo App Assignment', type: 'assignment', isPreview: false, order: 4 },
        ],
      },
      {
        id: 'mod_1_3',
        courseId: 'course_1',
        title: 'Node.js & Express Backend',
        order: 3,
        lessons: [
          { id: 'les_1_3_1', moduleId: 'mod_1_3', title: 'Node.js Fundamentals', type: 'video', duration: '28:30', isPreview: false, order: 1 },
          { id: 'les_1_3_2', moduleId: 'mod_1_3', title: 'Building REST APIs with Express', type: 'video', duration: '45:00', isPreview: false, order: 2 },
          { id: 'les_1_3_3', moduleId: 'mod_1_3', title: 'Authentication with JWT', type: 'video', duration: '38:20', isPreview: false, order: 3 },
        ],
      },
    ],
    createdAt: '2024-01-20T00:00:00Z',
    updatedAt: '2024-03-01T00:00:00Z',
  },
  {
    id: 'course_2',
    title: 'Data Science & Machine Learning with Python',
    slug: 'data-science-machine-learning-python',
    description: 'From pandas to neural networks. Master data science with real-world projects.',
    longDescription: 'Dive deep into data science and machine learning with Python. This course covers everything from data manipulation with pandas and NumPy, to building and deploying machine learning models with scikit-learn and TensorFlow. Includes 10 real-world projects.',
    thumbnail: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80',
    instructorId: 'instructor_2',
    instructorName: 'Marcus Johnson',
    instructorAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&q=80',
    category: 'Data Science',
    level: 'Intermediate',
    price: 94.99,
    isFree: false,
    isFeatured: true,
    isPublished: true,
    isApproved: true,
    rating: 4.9,
    reviewCount: 1923,
    enrolledCount: 8730,
    duration: '58 hours',
    tags: ['Python', 'Machine Learning', 'TensorFlow', 'Data Science', 'AI'],
    requirements: ['Basic Python knowledge', 'High school mathematics', 'Enthusiasm for data'],
    whatYouLearn: [
      'Manipulate data with pandas and NumPy',
      'Build ML models with scikit-learn',
      'Create neural networks with TensorFlow',
      'Visualize data with matplotlib and seaborn',
      'Deploy ML models to production',
    ],
    modules: [
      {
        id: 'mod_2_1',
        courseId: 'course_2',
        title: 'Python for Data Science',
        order: 1,
        lessons: [
          { id: 'les_2_1_1', moduleId: 'mod_2_1', title: 'Python Refresher for DS', type: 'video', duration: '30:00', isPreview: true, order: 1 },
          { id: 'les_2_1_2', moduleId: 'mod_2_1', title: 'NumPy Deep Dive', type: 'video', duration: '45:00', isPreview: false, order: 2 },
          { id: 'les_2_1_3', moduleId: 'mod_2_1', title: 'Pandas Mastery', type: 'video', duration: '52:00', isPreview: false, order: 3 },
          { id: 'les_2_1_4', moduleId: 'mod_2_1', title: 'Data Wrangling Quiz', type: 'quiz', isPreview: false, order: 4, quiz: { id: 'quiz_2', lessonId: 'les_2_1_4', questions: [{ id: 'q3', question: 'Which library is used for data manipulation in Python?', options: ['NumPy', 'pandas', 'matplotlib', 'scikit-learn'], correctIndex: 1 }] } },
        ],
      },
      {
        id: 'mod_2_2',
        courseId: 'course_2',
        title: 'Machine Learning Fundamentals',
        order: 2,
        lessons: [
          { id: 'les_2_2_1', moduleId: 'mod_2_2', title: 'Supervised vs Unsupervised Learning', type: 'video', duration: '25:00', isPreview: false, order: 1 },
          { id: 'les_2_2_2', moduleId: 'mod_2_2', title: 'Linear Regression Deep Dive', type: 'video', duration: '40:00', isPreview: false, order: 2 },
          { id: 'les_2_2_3', moduleId: 'mod_2_2', title: 'Classification Algorithms', type: 'video', duration: '48:00', isPreview: false, order: 3 },
        ],
      },
    ],
    createdAt: '2024-02-01T00:00:00Z',
    updatedAt: '2024-03-10T00:00:00Z',
  },
  {
    id: 'course_3',
    title: 'Cloud Architecture & DevOps Engineering',
    slug: 'cloud-architecture-devops',
    description: 'Master AWS, Docker, Kubernetes, CI/CD pipelines and infrastructure as code.',
    longDescription: 'Become a cloud and DevOps expert. This course covers AWS services in depth, containerization with Docker, orchestration with Kubernetes, and building robust CI/CD pipelines. Learn infrastructure as code with Terraform and Ansible.',
    thumbnail: 'https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?w=800&q=80',
    instructorId: 'instructor_1',
    instructorName: 'Dr. Sarah Chen',
    instructorAvatar: 'https://images.unsplash.com/photo-1494790108755-2616b612b1e0?w=100&q=80',
    category: 'DevOps',
    level: 'Advanced',
    price: 109.99,
    isFree: false,
    isFeatured: true,
    isPublished: true,
    isApproved: true,
    rating: 4.7,
    reviewCount: 1456,
    enrolledCount: 6210,
    duration: '65 hours',
    tags: ['AWS', 'Docker', 'Kubernetes', 'DevOps', 'CI/CD', 'Terraform'],
    requirements: ['Linux fundamentals', 'Basic networking knowledge', 'Programming experience'],
    whatYouLearn: [
      'Architect scalable AWS infrastructure',
      'Containerize apps with Docker',
      'Orchestrate containers with Kubernetes',
      'Build CI/CD pipelines with GitHub Actions',
      'Infrastructure as Code with Terraform',
    ],
    modules: [
      {
        id: 'mod_3_1',
        courseId: 'course_3',
        title: 'AWS Fundamentals',
        order: 1,
        lessons: [
          { id: 'les_3_1_1', moduleId: 'mod_3_1', title: 'AWS Global Infrastructure', type: 'video', duration: '22:00', isPreview: true, order: 1 },
          { id: 'les_3_1_2', moduleId: 'mod_3_1', title: 'EC2, S3, and VPC Deep Dive', type: 'video', duration: '55:00', isPreview: false, order: 2 },
          { id: 'les_3_1_3', moduleId: 'mod_3_1', title: 'AWS Architecture Patterns', type: 'pdf', isPreview: false, order: 3 },
        ],
      },
      {
        id: 'mod_3_2',
        courseId: 'course_3',
        title: 'Docker & Containerization',
        order: 2,
        lessons: [
          { id: 'les_3_2_1', moduleId: 'mod_3_2', title: 'Docker Fundamentals', type: 'video', duration: '35:00', isPreview: false, order: 1 },
          { id: 'les_3_2_2', moduleId: 'mod_3_2', title: 'Docker Compose & Networking', type: 'video', duration: '42:00', isPreview: false, order: 2 },
          { id: 'les_3_2_3', moduleId: 'mod_3_2', title: 'Containerization Assignment', type: 'assignment', isPreview: false, order: 3 },
        ],
      },
    ],
    createdAt: '2024-02-15T00:00:00Z',
    updatedAt: '2024-03-15T00:00:00Z',
  },
  {
    id: 'course_4',
    title: 'UI/UX Design Masterclass',
    slug: 'ui-ux-design-masterclass',
    description: 'Design stunning digital products with Figma. From wireframes to production-ready designs.',
    longDescription: 'Master the complete UI/UX design process from user research to high-fidelity prototypes. Learn Figma, design systems, accessibility, and how to collaborate with developers.',
    thumbnail: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&q=80',
    instructorId: 'instructor_2',
    instructorName: 'Marcus Johnson',
    instructorAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&q=80',
    category: 'Design',
    level: 'Beginner',
    price: 74.99,
    isFree: false,
    isFeatured: false,
    isPublished: true,
    isApproved: true,
    rating: 4.6,
    reviewCount: 987,
    enrolledCount: 4320,
    duration: '38 hours',
    tags: ['Figma', 'UI Design', 'UX Research', 'Prototyping', 'Design Systems'],
    requirements: ['No prior design experience needed', 'Figma free account'],
    whatYouLearn: ['Design with Figma', 'User research methods', 'Create design systems', 'Build interactive prototypes'],
    modules: [
      {
        id: 'mod_4_1',
        courseId: 'course_4',
        title: 'Design Principles',
        order: 1,
        lessons: [
          { id: 'les_4_1_1', moduleId: 'mod_4_1', title: 'Visual Design Fundamentals', type: 'video', duration: '28:00', isPreview: true, order: 1 },
          { id: 'les_4_1_2', moduleId: 'mod_4_1', title: 'Color Theory & Typography', type: 'video', duration: '32:00', isPreview: false, order: 2 },
        ],
      },
    ],
    createdAt: '2024-03-01T00:00:00Z',
    updatedAt: '2024-03-20T00:00:00Z',
  },
  {
    id: 'course_5',
    title: 'Cybersecurity Fundamentals & Ethical Hacking',
    slug: 'cybersecurity-ethical-hacking',
    description: 'Learn to think like a hacker to defend systems. CEH exam prep included.',
    longDescription: 'Comprehensive cybersecurity course covering network security, penetration testing, ethical hacking techniques, and security best practices. Prepares you for CEH certification.',
    thumbnail: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&q=80',
    instructorId: 'instructor_2',
    instructorName: 'Marcus Johnson',
    instructorAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&q=80',
    category: 'Cybersecurity',
    level: 'Intermediate',
    price: 99.99,
    isFree: false,
    isFeatured: false,
    isPublished: false,
    isApproved: false,
    rating: 0,
    reviewCount: 0,
    enrolledCount: 0,
    duration: '50 hours',
    tags: ['Security', 'Ethical Hacking', 'Penetration Testing', 'CEH'],
    requirements: ['Networking basics', 'Linux command line'],
    whatYouLearn: ['Network security fundamentals', 'Penetration testing', 'Vulnerability assessment'],
    modules: [
      {
        id: 'mod_5_1',
        courseId: 'course_5',
        title: 'Security Foundations',
        order: 1,
        lessons: [
          { id: 'les_5_1_1', moduleId: 'mod_5_1', title: 'Introduction to Cybersecurity', type: 'video', duration: '20:00', isPreview: true, order: 1 },
        ],
      },
    ],
    createdAt: '2024-03-10T00:00:00Z',
    updatedAt: '2024-03-10T00:00:00Z',
  },
];

export const mockEnrollments: Enrollment[] = [
  {
    id: 'enroll_1',
    studentId: 'student_1',
    courseId: 'course_1',
    enrolledAt: '2024-02-15T00:00:00Z',
    progress: 45,
    completedLessons: ['les_1_1_1', 'les_1_1_2', 'les_1_1_3', 'les_1_1_4', 'les_1_1_5'],
    lastAccessedLesson: 'les_1_2_1',
    quizScores: { quiz_1: 90 },
    isCompleted: false,
  },
  {
    id: 'enroll_2',
    studentId: 'student_1',
    courseId: 'course_2',
    enrolledAt: '2024-02-20T00:00:00Z',
    progress: 20,
    completedLessons: ['les_2_1_1', 'les_2_1_2'],
    lastAccessedLesson: 'les_2_1_2',
    quizScores: {},
    isCompleted: false,
  },
  {
    id: 'enroll_3',
    studentId: 'student_2',
    courseId: 'course_1',
    enrolledAt: '2024-02-18T00:00:00Z',
    progress: 78,
    completedLessons: ['les_1_1_1', 'les_1_1_2', 'les_1_1_3', 'les_1_1_4', 'les_1_1_5', 'les_1_2_1', 'les_1_2_2', 'les_1_2_3'],
    quizScores: { quiz_1: 100 },
    isCompleted: false,
  },
  {
    id: 'enroll_4',
    studentId: 'student_3',
    courseId: 'course_2',
    enrolledAt: '2024-03-05T00:00:00Z',
    progress: 60,
    completedLessons: ['les_2_1_1', 'les_2_1_2', 'les_2_1_3'],
    quizScores: {},
    isCompleted: false,
  },
];

export const mockCourseRequests: CourseRequest[] = [
  {
    id: 'req_1',
    instructorId: 'instructor_2',
    instructorName: 'Marcus Johnson',
    courseTitle: 'Advanced Deep Learning & NLP',
    courseDescription: 'Advanced course covering transformer architectures, BERT, GPT models, and production ML deployment.',
    category: 'Data Science',
    status: 'pending',
    submittedAt: '2024-03-15T00:00:00Z',
  },
  {
    id: 'req_2',
    instructorId: 'instructor_1',
    instructorName: 'Dr. Sarah Chen',
    courseTitle: 'Microservices Architecture with Go',
    courseDescription: 'Build scalable microservices using Go, gRPC, and event-driven architecture.',
    category: 'Backend Development',
    status: 'approved',
    submittedAt: '2024-03-10T00:00:00Z',
    reviewedAt: '2024-03-12T00:00:00Z',
    adminNote: 'Excellent proposal. Approved for immediate development.',
  },
];

export const mockReviews: Review[] = [
  {
    id: 'review_1',
    courseId: 'course_1',
    studentId: 'student_2',
    studentName: 'Emma Wilson',
    rating: 5,
    comment: 'Absolutely the best full-stack course I have taken. Dr. Sarah explains everything so clearly and the projects are real-world. Got a job offer 2 months after completing this!',
    createdAt: '2024-03-10T00:00:00Z',
  },
  {
    id: 'review_2',
    courseId: 'course_1',
    studentId: 'student_3',
    studentName: 'Carlos Rivera',
    rating: 5,
    comment: 'Outstanding course! The Node.js and PostgreSQL sections were particularly strong. I built my first production app using exactly what I learned here.',
    createdAt: '2024-03-15T00:00:00Z',
  },
  {
    id: 'review_3',
    courseId: 'course_1',
    studentId: 'admin_1',
    studentName: 'Alex Morgan',
    rating: 4,
    comment: 'Very comprehensive. The React section could go a bit deeper into advanced patterns, but overall this is a fantastic course for anyone starting out.',
    createdAt: '2024-03-18T00:00:00Z',
  },
  {
    id: 'review_4',
    courseId: 'course_2',
    studentId: 'student_3',
    studentName: 'Carlos Rivera',
    rating: 5,
    comment: 'Marcus is an incredible teacher. The ML fundamentals section changed how I think about data. Already applying these skills at work.',
    createdAt: '2024-03-20T00:00:00Z',
  },
  {
    id: 'review_5',
    courseId: 'course_2',
    studentId: 'student_2',
    studentName: 'Emma Wilson',
    rating: 5,
    comment: 'Best data science course on any platform, period. The pandas and NumPy deep dives alone are worth the price. Highly recommend!',
    createdAt: '2024-03-22T00:00:00Z',
  },
  {
    id: 'review_6',
    courseId: 'course_3',
    studentId: 'student_1',
    studentName: 'Jordan Lee',
    rating: 4,
    comment: 'The Docker and Kubernetes content is top-notch. I passed my AWS Solutions Architect exam after completing the AWS modules. Would love more Terraform content.',
    createdAt: '2024-03-25T00:00:00Z',
  },
];
